services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    container_name: library-api

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - /app/.venv

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16

    container_name: library-postgres

    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

  postgres_test:
    image: postgres:16

    container_name: library-postgres-test

    environment:
      POSTGRES_DB: library_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5433:5432"

  redis:
    image: redis:7

    container_name: library-redis

    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: library-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: library-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus