"""create notifications table

Revision ID: 55022d3a2d13
Revises: 2a491833ffa3
Create Date: 2026-05-08 03:23:43.423939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55022d3a2d13'
down_revision: Union[str, Sequence[str], None] = '2a491833ffa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('loan_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('LOAN_CREATED', 'LOAN_RETURNED', 'LOAN_CANCELLED', 'LOAN_DUE_SOON', 'LOAN_DUE_TODAY', 'LOAN_OVERDUE', name='notificationtype'), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
